### ISSUE TITLE
Rate limiting on toot deletions

### ISSUE THREAD

**Issue by MarkEEaton** [hughrun/ephemetoot#7] opened 2019-03-06 14:12 UTC
These posts from Eugen suggest a new rate limit for toot deletions:
https://mastodon.social/@Gargron/101588449409740014

**Comment by hughrun** [comment] 2019-03-07 09:00
Ouch, I didn't notice that.

Seems it came in with [v2.7.2](https://github.com/tootsuite/mastodon/releases/tag/v2.7.2)

We could probably deal with this within the checkToots function using something like: 
```
while deleted_count <= 30:
  // run deletion logic

if deleted_count > 30:
  print("Toot deletion rate limit reached. Sleeping for 30 minutes...")
  time.sleep(1800)
```

**Comment by hughrun** [comment] 2019-05-07 22:52
This API change was indeed implemented at https://github.com/tootsuite/mastodon/pull/10042 . I'll make some adjustments in the next few days.

**Comment by MarkEEaton** [comment] 2019-05-10 17:52
This makes a lot of sense, and I think it covers almost all use cases.

The corner case comes to mind is: what if someone deletes 20 toots, then 10 minutes later comes back to delete another 20?

**Comment by hughrun** [comment] 2019-05-10 22:02
Hmm, good point. It might be better to do error checking for `MastodonRatelimitError` instead or as well: https://mastodonpy.readthedocs.io/en/stable/#error-handling

**Comment by hughrun** [comment] 2019-05-19 03:44
The issue re `ratelimit_remaining` in https://github.com/hughrun/ephemetoot/pull/10 seems to be caused by `mastodon.py` initially defaulting to a general "300 operations" rate limit, and only moving to the deletions rate limit once a deletion is attempted. Not really sure how to get around this.

**Comment by MarkEEaton** [comment] 2019-05-19 04:22
That's what I found too when looking at the Mastodon.py code. If I'm understanding it correctly, Mastodon.py defaults to a `ratelimit_remaining` of `300` in its `__init__` method, as seen [here](https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L304), and then only adjusts it when an API call is made to mastodon, as seen [here](https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L2679). It doesn't seem like the assumption that `ratelimit_remaining` starts at `300` is necessarily correct. Could be an issue to raise at Mastodon.py?

**Comment by hughrun** [comment] 2019-05-19 04:39
From my testing I think the issue is more that it defaults to initially checking the less specific rate limit of 300 requests per 5 minutes, whereas what we want is the toot deletions rate limit. So mastodon.py probably needs to be updated to differentiate between the different limits.

**Comment by hughrun** [comment] 2019-05-19 04:48
Resolved with https://github.com/hughrun/ephemetoot/commit/824a6f7071898adede2774de7b6f9cfa00016096

**Closed by hughrun** 2019-05-19 04:48 UTC
Labels: bug
